### ISSUE TITLE
Remove "Repeat" option from alerts where it's unnecessary and add possibility to disable an alert

### ISSUE THREAD

**Issue by qwqatest** [Faifly/xDrip#200]
![Screenshot at Oct 14 18-44-08](https://user-images.githubusercontent.com/47991168/96012847-42262980-0e4d-11eb-9b3c-554674ef0ac0.png)

**Comment by qwqatest** [comment]
Probably, all alerts should be enabled by default
![Screenshot at Oct 23 19-13-01](https://user-images.githubusercontent.com/47991168/97027879-0897a180-1564-11eb-9e3b-637adde3fec6.png)

**Comment by Ivan-Skoryk** [comment]
[check here](https://github.com/Faifly/xDrip/pull/202#discussion_r511852310)
