### ISSUE TITLE
I was unable to restore connection or pair transmitter again until tapping on the "Forget this device" button in iOS settings 

### ISSUE THREAD

**Issue by qwqatest** [Faifly/xDrip#205]
I turned on Android phone with xDrip installed app on it for a short period of time (like several minutes), xDrip app wasn't running on Android. And after turning the Android phone off, readings were missing on iPhone for several hours. Then I've tried to unpair transmitter and pair it again but no luck. Only after tapping on the "Forget this device" button in iOS settings connection was restored successfully.
So, can we restore the connection without forgetting the device or at least show information that user have to forget device in the phone Settings manually?

Readings were missed for a long time  
![Screenshot at Oct 16 17-53-15](https://user-images.githubusercontent.com/47991168/96274669-77f81900-0fd9-11eb-8fcb-a604c4aa0c4f.png)
Log for the time when readings were missed
![Screenshot at Oct 16 17-53-37](https://user-images.githubusercontent.com/47991168/96274979-d6bd9280-0fd9-11eb-96b0-640945d1aba1.png)

Device was forgotten between 14:00 and 14:05
![Screenshot at Oct 16 14-16-42](https://user-images.githubusercontent.com/47991168/96275072-f5bc2480-0fd9-11eb-99e7-fa3281e67c29.png)

**Comment by Artem-Kalmykov** [comment]
There is no way to control that from the application side. Added a special handling for this error - when it happens user is notified that something went wrong with pairing and user is prompted to manually unpair the transmitter.

**Comment by qwqatest** [comment]
@Artem-Kalmykov The alert window appears many times in a row after clicking on the "Ok" button if you lock your phone screen with opened alert for some time (in my case it were like 2 hours)  on the "Statistics" screen and then try to close it.

[Screen Recording 2020-11-02 at 14.16.16.mov.zip](https://github.com/Faifly/xDrip/files/5475396/Screen.Recording.2020-11-02.at.14.16.16.mov.zip)
