### ISSUE TITLE
Add sending real stop request on the "Stop Sensor" button on the "Sensor" screen

### ISSUE THREAD

**Issue by qwqatest** [Faifly/xDrip#322]

**Comment by qwqatest** [comment]
After a user taps on the "Stop Sensor" button show the following text on the Main screen:
"Wait for sensor stopping"
When we got real ".stopped" status - show another text: "Sensor stopped"

**Comment by NSFriend** [comment]
If the sensor stop fails, then after receiving a response from the transmitter that the stop failed, the button in the settings will return to the "Stop Sensor" state and the application will behave as before the sensor stop, which will allow you to try to make a stop again.
