### ISSUE TITLE
Got "Initial Calibration" alert while "CalibrationState.okay", readings are working fine, but there is no any calibration saved in the app

### ISSUE THREAD

**Issue by qwqatest** [Faifly/xDrip#329]
It happened when transmitter and sensor weren't stopped but the app was reinstalled. Probably no need to show the "Initial Calibration" alert in this case
![Screenshot_at_Jun_10_17-41-33](https://user-images.githubusercontent.com/47991168/121709435-3a547d00-cae1-11eb-8072-2d37690bdf34.png)

**Comment by NSFriend** [comment]
Adjusted

 - For firmware version 2:

Initial calibration will be shown only if calibration status of last reading is .needsFirstCalibration  
Regular calibration will be shown only if calibration status of last reading is .needsSecondCalibration, .needsCalibration

 - For firmware version 1:
 Logic remains as was before.
