### ISSUE TITLE
xCode failing to build

### ISSUE THREAD

**Issue by gbrown18** [Faifly/xDrip#337]
On build xCode fails with error code: 

/Users/Gareth 1/Library/Developer/Xcode/DerivedData/xDrip-gtaspndzbqasqagmmcsrbavmogzt/Build/Intermediates.noindex/xDrip.build/Debug-iphoneos/xDrip.build/Script-58B4F6CE241164E4003C6D8F.sh: line 2: node: command not found
Command PhaseScriptExecution failed with a nonzero exit code

Unable to build project to device or simulator with the same error code each time.

**Comment by sepehrhosseini** [comment]
@gbrown18 how did you resolved this? I'm having the same issue

**Comment by NSFriend** [comment]
@sepehrhosseini Hello
Haven't delved into the question yet but have you tried waiting for all packages to load before building?
