### ISSUE TITLE
Values on the "Statistics" screen aren't correct and can be negative

### ISSUE THREAD

**Issue by qwqatest** [Faifly/xDrip#80]
At least values on the graph 
![Screenshot at Aug 27 12-11-33](https://user-images.githubusercontent.com/47991168/91439488-b5f87c80-e875-11ea-92ac-ad5f94dd710d.png)

**Comment by Artem-Kalmykov** [comment]
@qwqatest Please confirm it is fixed.

**Comment by qwqatest** [comment]
> @qwqatest Please confirm it is fixed.

Fixed
