### ISSUE TITLE
Mac:  Impossible to see and use "Slow" and "Other" food type - it doesn't scroll aside 

### ISSUE THREAD

**Issue by qwqatest** [Faifly/xDrip#93]
![Screenshot at Aug 28 18-16-31](https://user-images.githubusercontent.com/47991168/91584815-dc90e300-e95b-11ea-81b7-9df6c32da250.png)

**Comment by Artem-Kalmykov** [comment]
@qwqatest Please confirm it is fixed.

**Comment by qwqatest** [comment]
> @qwqatest Please confirm it is fixed.

@Artem-Kalmykov Fixed. Now it's possible but only by dragging the scroll bar
