### ISSUE TITLE
The first calibration takes only one value (instead of two) for successful result and it saved with many digits after the dot

### ISSUE THREAD

**Issue by qwqatest** [Faifly/xDrip#94]
![Screenshot at Aug 28 18-38-35](https://user-images.githubusercontent.com/47991168/91586213-b5d3ac00-e95d-11ea-8485-65858a7c2284.png)

![Screenshot at Aug 28 18-32-02](https://user-images.githubusercontent.com/47991168/91585929-642b2180-e95d-11ea-9643-b49609cc68bb.png)

**Comment by Artem-Kalmykov** [comment]
@qwqatest Please confirm it is fixed.

**Comment by qwqatest** [comment]
@Artem-Kalmykov @Ivan-Skoryk Why we have two digits after the dot if calibration values can only have one digit? I think we should display one digit after a dot 
![Screenshot at Sep 07 14-22-47](https://user-images.githubusercontent.com/47991168/92383065-5cfed300-f116-11ea-8dd8-d5afb35b7491.png)

**Comment by qwqatest** [comment]
Verified
