### ISSUE TITLE
Warming up message and timer aren't displayed until app restarted, if Initial Setup was used

### ISSUE THREAD

**Issue by qwqatest** [Faifly/xDrip#99]
<p align="center">
<img align="center" src="https://user-images.githubusercontent.com/47991168/91727604-98dfe880-ebaa-11ea-9e2f-4ed8a218f132.png" width="220" height="476">
<img align="center" src="https://user-images.githubusercontent.com/47991168/91727610-9b424280-ebaa-11ea-888c-29e1097b0234.png" width="220" height="476">
<img align="center" src="https://user-images.githubusercontent.com/47991168/91727611-9c736f80-ebaa-11ea-9643-e066c2f26593.png" width="220" height="476">
</p>

**Comment by Artem-Kalmykov** [comment]
@qwqatest Please confirm it is fixed.

**Comment by qwqatest** [comment]
@Artem-Kalmykov Fixed
